# -*- coding: utf-8 -*-
"""Nadja.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dFF7tbkoO2-Mk-f2l5-r9W4OjeetCKNu

# Nadja Karla Araújo de Lima 
###Matrícula: 11514339

###Curso: Ciência da Computação
"""

import numpy as np
import math
import pandas as pd
from statsmodels.stats.weightstats import DescrStatsW


print('Questão 1 \n')

# criação da tabela de frequencias
DF = pd.DataFrame({ 'Ponto médio': [90, 110, 130, 150, 170, 190], 'Nº de Mulheres': [30, 80, 40, 10, 4, 6]}, 
index=['80 |--- 100','100 |--- 120','120 |--- 140','140 |--- 160','160 |--- 180','180 |--- 200'] )

DF.index.name = 'Pressão Siatólica'
total = sum(DF['Nº de Mulheres'].values)
print(DF)
print('\nTotal nº de Mulheres:  ', total, '\n')


intervalos = DF.loc[DF['Ponto médio'] >= 120, ['Nº de Mulheres']].values
porcentagem =(sum(intervalos)/total)*100
porcentagemStr = '%.2f'%(porcentagem) + "%"

intervalos2 = DF.loc[DF['Ponto médio'] < 160, ['Nº de Mulheres']].values
qtdMulheres = sum(intervalos2)

intervalos3 = DF.loc[DF['Ponto médio'] >= 100, ['Nº de Mulheres']].values
qtdMulheres = sum(intervalos3)
porcentagem2 =(sum(intervalos3)/total)*100
porcentagemStr2 = '%.2f'%(porcentagem2) + "%"

#DF['Nº de Mulheres'].idxmax()

pontoM = DF['Ponto médio'].values
numMulheres = DF['Nº de Mulheres'].values
calcP = DescrStatsW(pontoM, numMulheres)
desvioP = calcP.std
desvioStr = '%.3f'%(desvioP)

mediaPonderada = calcP.mean
coeficientV = (desvioP/mediaPonderada)*100
coeficientStr = '%.3f'%(coeficientV) + '%'

"""**Questão a) A percentagem de mulheres que têm pressão igual ou maior que 120mm de Hg.**"""

intervalos = DF.loc[DF['Ponto médio'] >= 120, ['Nº de Mulheres']].values
porcentagem =(sum(intervalos)/total)*100
porcentagemStr = '%.2f'%(porcentagem) + "%"
print('\n a porcentagem é de: ' + porcentagemStr)

"""**Questão b)  O número de mulheres que têm pressão menor que 160 mm de Hg.**

---
"""

intervalos = DF.loc[DF['Ponto médio'] < 160, ['Nº de Mulheres']].values
qtdMulheres = sum(intervalos)
print('O número de mulheres que têm pressão menor que 160 mm de Hg é de', qtdMulheres)

"""**Questão c) O número de mulheres (e a percentagem) que têm pressão igual ou maior que 100mm de Hg.**"""

intervalos3 = DF.loc[DF['Ponto médio'] >= 100, ['Nº de Mulheres']].values
qtdMulheres = sum(intervalos3)
porcentagem2 =(sum(intervalos3)/total)*100
porcentagemStr2 = '%.2f'%(porcentagem2) + "%"
print('\n O número de mulheres é de: ' + str(qtdMulheres) + ' e a percentagem é de: '+  porcentagemStr2)

"""**Questão d) Qual a pressão sistólica mais frequente?**"""

DF['Nº de Mulheres'].idxmax()

"""**Questão e) Qual o desvio padrão e o coeficiente de variação para a pressão sistólica**"""

#desvio
pontoM = DF['Ponto médio'].values
numMulheres = DF['Nº de Mulheres'].values
calcP = DescrStatsW(pontoM, numMulheres)
desvioP = calcP.std
desvioStr = '%.3f'%(desvioP)

#coeficiente de variação
mediaPonderada = calcP.mean
coeficientV = (desvioP/mediaPonderada)*100
coeficientStr = '%.3f'%(coeficientV) + '%'

print('\n o desvio padrão é de: ' + str(desvioStr) + ' e o coeficiente de variação é de: '  + str(coeficientStr))

"""**Questão f) Construa o respectivo histograma**"""