# -*- coding: utf-8 -*-
"""Nadja.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dFF7tbkoO2-Mk-f2l5-r9W4OjeetCKNu
"""

import numpy
import math
import pandas as pd

print('Questão 1 : \n')
# criação da tabela de frequencias
DF = pd.DataFrame({ 'Ponto médio': [90, 110, 130, 150, 170, 190], 'Nº de Mulheres': [30, 80, 40, 10, 4, 6]}, 
index=['80 |--- 100','100 |--- 120','120 |--- 140','140 |--- 160','160 |--- 180','180 |--- 200'] )

DF.index.name = 'Pressão Siatólica'
total = sum(DF['Nº de Mulheres'].values)
print(DF)
print('\nTotal nº de Mulheres:  ', total, '\n')

# a) A percentagem de mulheres que têm pressão igual ou maior que 120mm de Hg.
# foi feito a soma das frequencias igual ou maior que 120 e dividida pelo total de mulheres.
#È efeituado a multiplicação para fazer a porcentagem.

intervalos1 = DF.loc[DF['Ponto médio'] >= 120, ['Nº de Mulheres']].values
porcentagem =(sum(intervalos)/total)*100
porcentagemStr = '%.2f'%(porcentagem) + "%";
#print('\n a porcentagem é de: ' + porcentagemStr)

"""**Questao a) A percentagem de mulheres que têm pressão igual ou maior que 120mm de Hg.**"""

intervalos = DF.loc[DF['Ponto médio'] >= 120, ['Nº de Mulheres']].values
porcentagem =(sum(intervalos)/total)*100
porcentagemStr = '%.2f'%(porcentagem) + "%";
print('\n a porcentagem é de: ' + porcentagemStr)

"""Questao b)  O número de mulheres que têm pressão menor que 160 mm de Hg.

---
"""